name: "\U0001F680 Feature Request"
description: Request a new feature
title: "Feature request: (short description of the feature)"
labels: ["enhancement", "needs triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: |
        Help us understand the problem that you are trying to solve, and why it is important to you.
        Provide as much detail as you are able.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your proposed feature that you see solving this problem for you. If you have a
        full or partial prototype implementation then please open a draft pull request and link to
        it here as well.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Example Use Cases
      description: |
        Provide some sample code snippets or shell scripts that show how **you** would use this feature as
        you have proposed it.
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: |
        How are you currently handling this? Describe any workarounds you're using.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (optional)
      description: If relevant to your feature request, please provide your environment details.
      value: |
        1. Operating system (e.g. Windows Server 2022; Amazon Linux 2023; etc.)
        2. Version of Cinema 4D
        3. Renderer used (e.g. Standard, Redshift, Arnold, etc.)
        4. Fleet configuration (Worker OS, GPU type if using Redshift)
    validations:
      required: false
